Watts/Watts/urls.py
from django.contrib import admin
from django.urls import path, include #Lembre de importar o include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')), 
    path('auth/', include('usuarios.urls')),
    

]

Watts/app/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', HomeViews.as_view(), name='home'),
    path('addLocacao/', AddLocacao.as_view(), name='addLocacao'),
    path('deleteLocacao/<int:locacao_id>/', DeleteLocacao.as_view(), name='deleteLocacao'),
    path('addComodo/', CriarComodo.as_view(), name='addComodo'),
    path('deleteComodo/<int:comodo_id>/', DeleteComodo.as_view(), name='deleteComodo'),
    path('addPontodeenergia/', CriarPontoDeEnergia.as_view(), name='addPontodeenergia'),
    path('deletePontodeenergia/<int:pontodeenergia_id>/', DeletePontodeenergia.as_view(), name='deletePontodeenergia'),
    path('calcular_custo_ponto/<int:pontodeenergia_id>/<int:horas>/', CalcularCustoPontoDeEnergia.as_view(), name='calcular_custo_ponto'),
    path('calcular_custo_comodo/<int:comodo_id>/', CalcularCustoComodo.as_view(), name='calcular_custo_comodo'),
    path('calcular_custo_locacao/<int:locacao_id>/', CalcularCustoLocacao.as_view(), name='calcular_custo_locacao'),
]

Watts/usuarios/urls.py
from django.urls import path
from . import views

app_name = 'usuarios'

urlpatterns = [
    path('', views.HomeViews.as_view(), name ='home'),
    path('cadastro/', views.CadastroView, name = 'cadastro'),
    path('login/', views.LoginView, name = 'login'),
]

Watts/usuarios/models.py
from django.db import models

# Create your models here.

Watts/usuarios/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate, login as auth_login, logout
from django.contrib.messages import constants
from django.views import View


def CadastroView(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')
        confirm_password = request.POST.get('confirm-password')

        if password != confirm_password:
            messages.add_message(request, constants.ERROR, "As senhas não coincidem")
            return render(request, 'cadastro.html', {
                'username': username,
                'email': email,
            })

        if User.objects.filter(email=email).exists():
            messages.add_message(request, constants.ERROR, "Email já cadastrado")
            return render(request, 'cadastro.html', {
                'username': username,
            })

        if User.objects.filter(username=username).exists():
            messages.add_message(request, constants.ERROR, "Nome já cadastrado")
            return render(request, 'cadastro.html', {
                'email': email,
            })

        user = User.objects.create_user(username=username, email=email, password=password)
        user.save()

        messages.success(request, "Usuário cadastrado com sucesso!")
        return render(request, 'login.html')
    else:
        return render(request, 'cadastro.html')

def LoginView(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            auth_login(request, user)
            return render(request, 'home.html')
        else:
            messages.add_message(request, constants.ERROR, 'Usuário ou senha inválidos')
            return render(request, 'login.html', {
                'username': username,
            })
    else:
        return render(request, 'login.html')



class HomeViews(View):
    def get(self, request):
        return render(request, 'home.html')

Watts/usuarios/templates/cadastro.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />

    <title>Register</title>
  </head>
  <body>
    <div class="container">
      <h1>Register</h1>

      {% if messages %}
        {% for message in messages %}
          <section class="alert {{message.tags}}">{{message}}</section>
        {% endfor %}
      {% endif %}

      <form action="{% url 'usuarios:cadastro' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
          <label for="username">Username</label>
          <input
            name="username"
            type="text"
            class="form-control"
            id="username"
            placeholder="Username"
            required
            value="{{ username }}"
          />
        </div>

        <div class="form-group">
          <label for="email">Email address</label>
          <input
            name="email"
            type="email"
            class="form-control"
            id="email"
            aria-describedby="emailHelp"
            placeholder="Enter email"
            required
            value="{{ email }}"
          />
          <small id="emailHelp" class="form-text text-muted">
            We'll never share your email with anyone else.
          </small>
        </div>

        <div class="form-group">
          <label for="password">Password</label>
          <input
            name="password"
            type="password"
            class="form-control"
            id="password"
            placeholder="Password"
            required
          />
        </div>

        <div class="form-group">
          <label for="confirm-password">Confirm Password</label>
          <input
            name="confirm-password"
            type="password"
            class="form-control"
            id="confirm-password"
            placeholder="Confirm Password"
            required
          />
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
        <br>
      </form>
      <br>
      <a href="{% url 'usuarios:login' %}">Login</a>
    </div>

    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

</html> 

Watts/usuarios/templates/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />

    <title>Login</title>
  </head>
  <body>
    <div class="container">
      <h1>Login</h1>

      {% if messages %}
        {% for message in messages %}
          <section class="alert {{message.tags}}">{{message}}</section>
        {% endfor %}
      {% endif %}

      <form action="{% url 'usuarios:login' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
          <label for="username">Username</label>
          <input
            name="username"
            type="text"
            class="form-control"
            id="username"
            placeholder="Username"
            required
            value="{{ username }}"
          />
        </div>

        <div class="form-group">
          <label for="password">Password</label>
          <input
            name="password"
            type="password"
            class="form-control"
            id="password"
            placeholder="Password"
            required
          />
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
        <br>
      </form>
      <br>
      <a href="{% url 'usuarios:cadastro' %}">Register</a>
    </div>

    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
  </body>
</html>